### PR TITLE
WIP: Outsourcing dtool-lookup-client API

### PR DESCRIPTION
**Pull request by jotelha**
Hello Tjelvar,

again this is not a ready-to-merge PR, but meant as a starting point for discussion.

We have modified your `dtool-lookup-client` here a bit 

* to look up not the token, but the lookup server's credentials from the configuration instead
* use the same Python API as our GUI in order to offer comparable operations from the command line

For now, Lars' 

    https://github.com/IMTEK-Simulation/dtool-lookup-gui/blob/master/dtool_lookup_gui/LookupClient.py

is imported via

    from dtool_lookup_gui.LookupClient import LookupClient

and wrapped via some async_to_sync decorators

    from asgiref.sync import async_to_sync

from https://github.com/django/asgiref, just meant as a quick and dirty experiment. On the long term, something like `LookupClient` should probably move to some independent `dtool-lookup-client-api` that both CLI and GUI client depend on. That's what I would like to discuss. What do you think?

The modifications allow to retrieve results in text format for further processing. The introduced `dtool query` allows direct queries via the server's direct mongo plugin https://github.com/IMTEK-Simulation/dtool-lookup-server-direct-mongo-plugin. 

Here a simple example counting all datasets that match a certain query

```
$ dtool query -m '{"creator_username":"hoermann4","readme.mode":"trial"}' | grep frozen_at | wc -l
603
```

and narrowing down the selection by dates or regex patterns

```console
$ dtool query -m '{"creator_username":"hoermann4","readme.mode":"trial", "name": {"$regex":"minimization$"}, "readme.creation_date":{"$gt":"2020-08-05", "$lt": "2020-08-06"}}'
[
  {
    "base_uri": "smb://jh1130",
    "created_at": "Wed, 05 Aug 2020 16:04:32 GMT",
    "creator_username": "hoermann4",
    "dtoolcore_version": "3.17.0",
    "frozen_at": "Mon, 07 Sep 2020 18:21:42 GMT",
    "name": "2020-08-05-17-50-45-127872-lammpsrelaxedboxminimization",
    "tags": [],
    "type": "dataset",
    "uri": "smb://jh1130/3413f464-d955-43a4-9b6b-e239d85eecf1",
    "uuid": "3413f464-d955-43a4-9b6b-e239d85eecf1"
  },
  {
    "base_uri": "smb://jh1130",
    "created_at": "Wed, 05 Aug 2020 16:11:03 GMT",
    "creator_username": "hoermann4",
    "dtoolcore_version": "3.17.0",
    "frozen_at": "Mon, 07 Sep 2020 18:22:48 GMT",
    "name": "2020-08-05-18-07-28-848226-lammpsrelaxedboxminimization",
    "tags": [],
    "type": "dataset",
    "uri": "smb://jh1130/8ce577bf-50dc-4dd9-96cb-aaedd5230826",
    "uuid": "8ce577bf-50dc-4dd9-96cb-aaedd5230826"
  }
]
```

### CODE REVIEW

**Comment by pastewka** [comment]
A couple of comments:
* `LookupClient` is designed for asynchronous operation using `aiohttp`. (The synchronous equivalent is `requests`, which has *almost* the same API.)
* The asynchronous stuff is probably incompatible with what you'd want for a CLI.
* The question is whether it is worth to rely on something like this `sync_to_sync` stuff or whether it may be less painful to just implement it twice.
* The latter is probably only feasible as long as the API remains as simple as it is now.

**Comment by pastewka** [comment]
(In any case, having either or both as a reusable component in a library would be useful.)

**Comment by jotelha** [comment]
> A couple of comments:
> 
>     * `LookupClient` is designed for asynchronous operation using `aiohttp`. (The synchronous equivalent is `requests`, which has _almost_ the same API.)
> 
>     * The asynchronous stuff is probably incompatible with what you'd want for a CLI.
> 
>     * The question is whether it is worth to rely on something like this `sync_to_sync` stuff or whether it may be less painful to just implement it twice.
I took this `async_to_sync` decorator from  https://www.aeracode.org/2018/02/19/python-async-simplified/, section `Async From Sync` and would prefer not to use it unless something similar exists within the standard Python libraries without introducing further dependencies. I simply used that to keep the effort for this "experiment" as minimal as possible.

Another option would be to just insert a very simple wrapper without external, dependencies, as discussed on https://stackoverflow.com/questions/55152952/duplication-of-code-for-synchronous-and-asynchronous-implementations, or here https://gist.github.com/phizaz/20c36c6734878c6ec053245a477572ec#file-async-py. 

> 
>     * The latter is probably only feasible as long as the API remains as simple as it is now.

**Comment by tjelvar-olsson** [comment]
Hi @jotelha , hi @pastewka,

This looks really interesting! 👍

We should have a chat about it. I'll send an email for us to try and coordinate a time.

**Comment by jotelha** [comment]
API now implemented at https://github.com/IMTEK-Simulation/dtool-lookup-api/,
rudimentary fork of this client utilizing API at https://github.com/IMTEK-Simulation/dtool-lookup-client.

**Pull request closed without merging**
